from datetime import UTC, datetime
from uuid import UUID, uuid4

from sqlalchemy import CheckConstraint, Index, Text, text
from sqlmodel import Field, SQLModel


class NetworkRecord(SQLModel):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    deleted_at: datetime | None = Field(default=None, index=True)


class NetworkDevice(NetworkRecord, table=True):
    __tablename__ = "network_devices"
    __table_args__ = (
        CheckConstraint(
            "role IN ('router', 'firewall', 'switch', 'access_point', 'server', "
            "'nas', 'client', 'iot', 'printer', 'controller', 'other')",
            name="ck_network_devices_role",
        ),
        Index(
            "uq_network_devices_active_asset",
            "asset_id",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
    )

    asset_id: UUID = Field(foreign_key="assets.id", index=True)
    role: str = Field(default="other", index=True, max_length=30)
    hostname: str | None = Field(default=None, index=True, max_length=253)
    management_url: str | None = Field(default=None, max_length=1000)
    notes: str | None = Field(default=None, sa_type=Text)


class NetworkSegment(NetworkRecord, table=True):
    __tablename__ = "network_segments"
    __table_args__ = (
        CheckConstraint(
            "vlan_id IS NULL OR (vlan_id >= 1 AND vlan_id <= 4094)",
            name="ck_network_segments_vlan_id",
        ),
        Index(
            "uq_network_segments_active_name",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
        Index(
            "uq_network_segments_active_vlan",
            "vlan_id",
            unique=True,
            sqlite_where=text("deleted_at IS NULL AND vlan_id IS NOT NULL"),
        ),
    )

    name: str = Field(index=True, max_length=150)
    cidr: str = Field(index=True, max_length=64)
    vlan_id: int | None = Field(default=None, index=True, ge=1, le=4094)
    gateway: str | None = Field(default=None, max_length=64)
    dns_servers_json: str = Field(default="[]", sa_type=Text)
    description: str | None = Field(default=None, sa_type=Text)


class NetworkInterface(NetworkRecord, table=True):
    __tablename__ = "network_interfaces"
    __table_args__ = (
        CheckConstraint(
            "interface_type IN ('ethernet', 'wifi', 'fiber', 'virtual', 'cellular', 'other')",
            name="ck_network_interfaces_type",
        ),
        CheckConstraint(
            "poe_mode IN ('none', 'source', 'sink', 'passive', 'unknown')",
            name="ck_network_interfaces_poe_mode",
        ),
        CheckConstraint(
            "speed_mbps IS NULL OR speed_mbps > 0",
            name="ck_network_interfaces_speed",
        ),
        CheckConstraint(
            "logical_interface_id IS NULL OR logical_interface_id <> id",
            name="ck_network_interfaces_logical_interface_distinct",
        ),
        Index(
            "uq_network_interfaces_active_name",
            "network_device_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
        Index(
            "uq_network_interfaces_active_mac",
            "mac_address",
            unique=True,
            sqlite_where=text("deleted_at IS NULL AND mac_address IS NOT NULL"),
        ),
    )

    network_device_id: UUID = Field(foreign_key="network_devices.id", index=True)
    logical_interface_id: UUID | None = Field(
        default=None,
        foreign_key="network_interfaces.id",
        index=True,
    )
    name: str = Field(index=True, max_length=100)
    interface_type: str = Field(default="ethernet", index=True, max_length=20)
    mac_address: str | None = Field(default=None, index=True, max_length=17)
    speed_mbps: int | None = Field(default=None, ge=1)
    poe_mode: str = Field(default="none", max_length=20)
    enabled: bool = Field(default=True, index=True)
    description: str | None = Field(default=None, sa_type=Text)
    autogenerated: bool = Field(default=False, index=True)
    port_group: str | None = Field(default=None, max_length=30)
    manually_customized: bool = Field(default=False)


class NetworkAddress(NetworkRecord, table=True):
    __tablename__ = "network_addresses"
    __table_args__ = (
        CheckConstraint(
            "assignment_type IN ('static', 'dhcp', 'reservation', 'link_local', 'unknown')",
            name="ck_network_addresses_assignment_type",
        ),
        Index(
            "uq_network_addresses_active_interface_address",
            "interface_id",
            "address",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
        Index(
            "uq_network_addresses_active_segment_address",
            "segment_id",
            "address",
            unique=True,
            sqlite_where=text("deleted_at IS NULL AND segment_id IS NOT NULL"),
        ),
    )

    interface_id: UUID = Field(foreign_key="network_interfaces.id", index=True)
    segment_id: UUID | None = Field(default=None, foreign_key="network_segments.id", index=True)
    address: str = Field(index=True, max_length=64)
    assignment_type: str = Field(default="unknown", index=True, max_length=20)
    hostname: str | None = Field(default=None, index=True, max_length=253)
    is_primary: bool = Field(default=False, index=True)
    notes: str | None = Field(default=None, sa_type=Text)


class NetworkConnection(NetworkRecord, table=True):
    __tablename__ = "network_connections"
    __table_args__ = (
        CheckConstraint(
            "source_interface_id <> target_interface_id",
            name="ck_network_connections_distinct_endpoints",
        ),
        CheckConstraint(
            "connection_type IN ('physical', 'logical', 'wireless')",
            name="ck_network_connections_type",
        ),
        CheckConstraint(
            "status IN ('active', 'planned', 'inactive')",
            name="ck_network_connections_status",
        ),
        Index(
            "uq_network_connections_active_endpoints",
            "source_interface_id",
            "target_interface_id",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
    )

    source_interface_id: UUID = Field(foreign_key="network_interfaces.id", index=True)
    target_interface_id: UUID = Field(foreign_key="network_interfaces.id", index=True)
    connection_type: str = Field(default="physical", index=True, max_length=20)
    status: str = Field(default="active", index=True, max_length=20)
    cable_type: str | None = Field(default=None, max_length=100)
    cable_label: str | None = Field(default=None, index=True, max_length=100)
    description: str | None = Field(default=None, sa_type=Text)
